
h_2019 = {'Akoni': ['ep12', 'East Pacific'],
 'Alvin': ['ep01', 'East Pacific'],
 'Andrea': ['al01', 'Atlantic'],
 'Barbara': ['ep02', 'East Pacific'],
 'Barry': ['al02', 'Atlantic'],
 'Chantal': ['al04', 'Atlantic'],
 'Cosme': ['ep03', 'East Pacific'],
 'Dalila': ['ep05', 'East Pacific'],
 'Dorian': ['al05', 'Atlantic'],
 'Erick': ['ep06', 'East Pacific'],
 'Erin': ['al06', 'Atlantic'],
 'Fernand': ['al07', 'Atlantic'],
 'Flossie': ['ep07', 'East Pacific'],
 'Four-e': ['ep04', 'East Pacific'],
 'Gabrielle': ['al08', 'Atlantic'],
 'Gil': ['ep08', 'East Pacific'],
 'Henriette': ['ep09', 'East Pacific'],
 'Humberto': ['al09', 'Atlantic'],
 'Imelda': ['al11', 'Atlantic'],
 'Ivo': ['ep10', 'East Pacific'],
 'Jerry': ['al10', 'Atlantic'],
 'Juliette': ['ep11', 'East Pacific'],
 'Karen': ['al12', 'Atlantic'],
 'Kiko': ['ep13', 'East Pacific'],
 'Lorena': ['ep15', 'East Pacific'],
 'Lorenzo': ['al13', 'Atlantic'],
 'Mario': ['ep14', 'East Pacific'],
 'Narda': ['ep16', 'East Pacific'],
 'Three': ['al03', 'Atlantic']}

h_2018 = {'Alberto': ['al01', 'Atlantic'],
 'Aletta': ['ep02', 'East Pacific'],
 'Beryl': ['al02', 'Atlantic'],
 'Bud': ['ep03', 'East Pacific'],
 'Carlotta': ['ep04', 'East Pacific'],
 'Chris': ['al03', 'Atlantic'],
 'Daniel': ['ep05', 'East Pacific'],
 'Debby': ['al04', 'Atlantic'],
 'Eleven': ['al11', 'Atlantic'],
 'Emilia': ['ep06', 'East Pacific'],
 'Ernesto': ['al05', 'Atlantic'],
 'Fabio': ['ep07', 'East Pacific'],
 'Florence': ['al06', 'Atlantic'],
 'Gilma': ['ep08', 'East Pacific'],
 'Gordon': ['al07', 'Atlantic'],
 'Hector': ['ep10', 'East Pacific'],
 'Helene': ['al08', 'Atlantic'],
 'Ileana': ['ep11', 'East Pacific'],
 'Isaac': ['al09', 'Atlantic'],
 'John': ['ep12', 'East Pacific'],
 'Joyce': ['al10', 'Atlantic'],
 'Kirk': ['al12', 'Atlantic'],
 'Kristy': ['ep13', 'East Pacific'],
 'Lane': ['ep14', 'East Pacific'],
 'Leslie': ['al13', 'Atlantic'],
 'Michael': ['al14', 'Atlantic'],
 'Miriam': ['ep15', 'East Pacific'],
 'Nadine': ['al15', 'Atlantic'],
 'Nine-e': ['ep09', 'East Pacific'],
 'Nineteen-e': ['ep19', 'East Pacific'],
 'Norman': ['ep16', 'East Pacific'],
 'Olivia': ['ep17', 'East Pacific'],
 'Oscar': ['al16', 'Atlantic'],
 'Paul': ['ep18', 'East Pacific'],
 'Rosa': ['ep20', 'East Pacific'],
 'Sergio': ['ep21', 'East Pacific'],
 'Tara': ['ep22', 'East Pacific'],
 'Vicente': ['ep23', 'East Pacific'],
 'Walaka': ['ep01', 'East Pacific'],
 'Willa': ['ep24', 'East Pacific'],
 'Xavier': ['ep25', 'East Pacific']}

h_2017 = {'Adrian': ['ep01', 'East Pacific'],
 'Arlene': ['al01', 'Atlantic'],
 'Beatriz': ['ep02', 'East Pacific'],
 'Bret': ['al02', 'Atlantic'],
 'Calvin': ['ep03', 'East Pacific'],
 'Cindy': ['al03', 'Atlantic'],
 'Don': ['al05', 'Atlantic'],
 'Dora': ['ep04', 'East Pacific'],
 'Eight-e': ['ep08', 'East Pacific'],
 'Eleven-e': ['ep11', 'East Pacific'],
 'Emily': ['al06', 'Atlantic'],
 'Eugene': ['ep05', 'East Pacific'],
 'Fernanda': ['ep06', 'East Pacific'],
 'Four': ['al04', 'Atlantic'],
 'Franklin': ['al07', 'Atlantic'],
 'Gert': ['al08', 'Atlantic'],
 'Greg': ['ep07', 'East Pacific'],
 'Harvey': ['al09', 'Atlantic'],
 'Hilary': ['ep09', 'East Pacific'],
 'Irma': ['al11', 'Atlantic'],
 'Irwin': ['ep10', 'East Pacific'],
 'Jose': ['al12', 'Atlantic'],
 'Jova': ['ep12', 'East Pacific'],
 'Katia': ['al13', 'Atlantic'],
 'Kenneth': ['ep13', 'East Pacific'],
 'Lee': ['al14', 'Atlantic'],
 'Lidia': ['ep14', 'East Pacific'],
 'Maria': ['al15', 'Atlantic'],
 'Max': ['ep16', 'East Pacific'],
 'Nate': ['al16', 'Atlantic'],
 'Norma': ['ep17', 'East Pacific'],
 'Ophelia': ['al17', 'Atlantic'],
 'Otis': ['ep15', 'East Pacific'],
 'Philippe': ['al18', 'Atlantic'],
 'Pilar': ['ep18', 'East Pacific'],
 'Ramon': ['ep19', 'East Pacific'],
 'Rina': ['al19', 'Atlantic'],
 'Selma': ['ep20', 'East Pacific'],
 'Ten': ['al10', 'Atlantic']}

h_2016 = {'Agatha': ['ep02', 'East Pacific'],
 'Alex': ['al01', 'Atlantic'],
 'Blas': ['ep03', 'East Pacific'],
 'Bonnie': ['al02', 'Atlantic'],
 'Celia': ['ep04', 'East Pacific'],
 'Colin': ['al03', 'Atlantic'],
 'Danielle': ['al04', 'Atlantic'],
 'Darby': ['ep05', 'East Pacific'],
 'Earl': ['al05', 'Atlantic'],
 'Eight': ['al08', 'Atlantic'],
 'Estelle': ['ep06', 'East Pacific'],
 'Fiona': ['al06', 'Atlantic'],
 'Frank': ['ep07', 'East Pacific'],
 'Gaston': ['al07', 'Atlantic'],
 'Georgette': ['ep08', 'East Pacific'],
 'Hermine': ['al09', 'Atlantic'],
 'Howard': ['ep09', 'East Pacific'],
 'Ian': ['al10', 'Atlantic'],
 'Ivette': ['ep10', 'East Pacific'],
 'Javier': ['ep11', 'East Pacific'],
 'Julia': ['al11', 'Atlantic'],
 'Karl': ['al12', 'Atlantic'],
 'Kay': ['ep12', 'East Pacific'],
 'Lester': ['ep13', 'East Pacific'],
 'Lisa': ['al13', 'Atlantic'],
 'Madeline': ['ep14', 'East Pacific'],
 'Matthew': ['al14', 'Atlantic'],
 'Newton': ['ep15', 'East Pacific'],
 'Nicole': ['al15', 'Atlantic'],
 'One-e': ['ep01', 'East Pacific'],
 'Orlene': ['ep16', 'East Pacific'],
 'Otto': ['ep22', 'East Pacific'],
 'Paine': ['ep17', 'East Pacific'],
 'Roslyn': ['ep18', 'East Pacific'],
 'Seymour': ['ep20', 'East Pacific'],
 'Tina': ['ep21', 'East Pacific'],
 'Ulika': ['ep19', 'East Pacific']}

h_2015 = {'Ana': ['al01', 'Atlantic'],
 'Andres': ['ep01', 'East Pacific'],
 'Bill': ['al02', 'Atlantic'],
 'Blanca': ['ep02', 'East Pacific'],
 'Carlos': ['ep03', 'East Pacific'],
 'Claudette': ['al03', 'Atlantic'],
 'Danny': ['al04', 'Atlantic'],
 'Dolores': ['ep05', 'East Pacific'],
 'Eight-e': ['ep08', 'East Pacific'],
 'Eleven-e': ['ep11', 'East Pacific'],
 'Enrique': ['ep06', 'East Pacific'],
 'Erika': ['al05', 'Atlantic'],
 'Felicia': ['ep07', 'East Pacific'],
 'Four-e': ['ep04', 'East Pacific'],
 'Fred': ['al06', 'Atlantic'],
 'Grace': ['al07', 'Atlantic'],
 'Guillermo': ['ep09', 'East Pacific'],
 'Henri': ['al08', 'Atlantic'],
 'Hilda': ['ep10', 'East Pacific'],
 'Ida': ['al10', 'Atlantic'],
 'Ignacio': ['ep12', 'East Pacific'],
 'Jimena': ['ep13', 'East Pacific'],
 'Joaquin': ['al11', 'Atlantic'],
 'Kate': ['al12', 'Atlantic'],
 'Kevin': ['ep14', 'East Pacific'],
 'Linda': ['ep15', 'East Pacific'],
 'Marty': ['ep17', 'East Pacific'],
 'Nine': ['al09', 'Atlantic'],
 'Nora': ['ep18', 'East Pacific'],
 'Olaf': ['ep19', 'East Pacific'],
 'Patricia': ['ep20', 'East Pacific'],
 'Rick': ['ep21', 'East Pacific'],
 'Sandra': ['ep22', 'East Pacific'],
 'Sixteen-e': ['ep16', 'East Pacific']}

h_2014 = {'Amanda': ['ep01', 'East Pacific'],
 'Arthur': ['al01', 'Atlantic'],
 'Bertha': ['al03', 'Atlantic'],
 'Boris': ['ep02', 'East Pacific'],
 'Cristina': ['ep03', 'East Pacific'],
 'Cristobal': ['al04', 'Atlantic'],
 'Dolly': ['al05', 'Atlantic'],
 'Douglas': ['ep04', 'East Pacific'],
 'Edouard': ['al06', 'Atlantic'],
 'Elida': ['ep05', 'East Pacific'],
 'Fausto': ['ep06', 'East Pacific'],
 'Fay': ['al07', 'Atlantic'],
 'Genevieve': ['ep07', 'East Pacific'],
 'Gonzalo': ['al08', 'Atlantic'],
 'Hanna': ['al09', 'Atlantic'],
 'Hernan': ['ep08', 'East Pacific'],
 'Iselle': ['ep09', 'East Pacific'],
 'Julio': ['ep10', 'East Pacific'],
 'Karina': ['ep11', 'East Pacific'],
 'Lowell': ['ep12', 'East Pacific'],
 'Marie': ['ep13', 'East Pacific'],
 'Norbert': ['ep14', 'East Pacific'],
 'Odile': ['ep15', 'East Pacific'],
 'Polo': ['ep17', 'East Pacific'],
 'Rachel': ['ep18', 'East Pacific'],
 'Simon': ['ep19', 'East Pacific'],
 'Sixteen-e': ['ep16', 'East Pacific'],
 'Trudy': ['ep20', 'East Pacific'],
 'Two': ['al02', 'Atlantic'],
 'Vance': ['ep21', 'East Pacific']}

h_2013 = {'Alvin': ['ep01', 'East Pacific'],
 'Andrea': ['al01', 'Atlantic'],
 'Barbara': ['ep02', 'East Pacific'],
 'Barry': ['al02', 'Atlantic'],
 'Chantal': ['al03', 'Atlantic'],
 'Cosme': ['ep03', 'East Pacific'],
 'Dalila': ['ep04', 'East Pacific'],
 'Dorian': ['al04', 'Atlantic'],
 'Eight': ['al08', 'Atlantic'],
 'Erick': ['ep05', 'East Pacific'],
 'Erin': ['al05', 'Atlantic'],
 'Fernand': ['al06', 'Atlantic'],
 'Flossie': ['ep06', 'East Pacific'],
 'Gabrielle': ['al07', 'Atlantic'],
 'Gil': ['ep07', 'East Pacific'],
 'Henriette': ['ep08', 'East Pacific'],
 'Humberto': ['al09', 'Atlantic'],
 'Ingrid': ['al10', 'Atlantic'],
 'Ivo': ['ep09', 'East Pacific'],
 'Jerry': ['al11', 'Atlantic'],
 'Juliette': ['ep10', 'East Pacific'],
 'Karen': ['al12', 'Atlantic'],
 'Kiko': ['ep11', 'East Pacific'],
 'Lorena': ['ep12', 'East Pacific'],
 'Lorenzo': ['al13', 'Atlantic'],
 'Manuel': ['ep13', 'East Pacific'],
 'Melissa': ['al14', 'Atlantic'],
 'Narda': ['ep14', 'East Pacific'],
 'Octave': ['ep15', 'East Pacific'],
 'Priscilla': ['ep16', 'East Pacific'],
 'Raymond': ['ep17', 'East Pacific'],
 'Sonia': ['ep18', 'East Pacific']}

h_2012 = {'Alberto': ['al01', 'Atlantic'],
 'Aletta': ['ep01', 'East Pacific'],
 'Beryl': ['al02', 'Atlantic'],
 'Bud': ['ep02', 'East Pacific'],
 'Carlotta': ['ep03', 'East Pacific'],
 'Chris': ['al03', 'Atlantic'],
 'Daniel': ['ep04', 'East Pacific'],
 'Debby': ['al04', 'Atlantic'],
 'Emilia': ['ep05', 'East Pacific'],
 'Ernesto': ['al05', 'Atlantic'],
 'Fabio': ['ep06', 'East Pacific'],
 'Florence': ['al06', 'Atlantic'],
 'Gilma': ['ep07', 'East Pacific'],
 'Gordon': ['al08', 'Atlantic'],
 'Hector': ['ep08', 'East Pacific'],
 'Helene': ['al07', 'Atlantic'],
 'Ileana': ['ep09', 'East Pacific'],
 'Isaac': ['al09', 'Atlantic'],
 'John': ['ep10', 'East Pacific'],
 'Joyce': ['al10', 'Atlantic'],
 'Kirk': ['al11', 'Atlantic'],
 'Kristy': ['ep11', 'East Pacific'],
 'Lane': ['ep12', 'East Pacific'],
 'Leslie': ['al12', 'Atlantic'],
 'Michael': ['al13', 'Atlantic'],
 'Miriam': ['ep13', 'East Pacific'],
 'Nadine': ['al14', 'Atlantic'],
 'Norman': ['ep14', 'East Pacific'],
 'Olivi': ['ep15', 'East Pacific'],
 'Oscar': ['al15', 'Atlantic'],
 'Patty': ['al16', 'Atlantic'],
 'Paul': ['ep16', 'East Pacific'],
 'Rafael': ['al17', 'Atlantic'],
 'Rosa': ['ep17', 'East Pacific'],
 'Sandy': ['al18', 'Atlantic'],
 'Tony': ['al19', 'Atlantic']}

h_2011 = {'Adrian': ['ep01', 'East Pacific'],
 'Arlene': ['al01', 'Atlantic'],
 'Beatriz': ['ep02', 'East Pacific'],
 'Bret': ['al02', 'Atlantic'],
 'Calvin': ['ep03', 'East Pacific'],
 'Cindy': ['al03', 'Atlantic'],
 'Don': ['al04', 'Atlantic'],
 'Dora': ['ep04', 'East Pacific'],
 'Eight-e': ['ep08', 'East Pacific'],
 'Emily': ['al05', 'Atlantic'],
 'Eugene': ['ep05', 'East Pacific'],
 'Franklin': ['al06', 'Atlantic'],
 'Frenanda': ['ep06', 'East Pacific'],
 'Gert': ['al07', 'Atlantic'],
 'Greg': ['ep07', 'East Pacific'],
 'Harvey': ['al08', 'Atlantic'],
 'Hilary': ['ep09', 'East Pacific'],
 'Irene': ['al09', 'Atlantic'],
 'Irwin': ['ep11', 'East Pacific'],
 'Jose': ['al11', 'Atlantic'],
 'Jova': ['ep10', 'East Pacific'],
 'Katia': ['al12', 'Atlantic'],
 'Kenneth': ['ep13', 'East Pacific'],
 'Lee': ['al13', 'Atlantic'],
 'Maria': ['al14', 'Atlantic'],
 'Nate': ['al15', 'Atlantic'],
 'Ophelia': ['al16', 'Atlantic'],
 'Philippe': ['al17', 'Atlantic'],
 'Rina': ['al18', 'Atlantic'],
 'Sean': ['al19', 'Atlantic'],
 'Ten': ['al10', 'Atlantic'],
 'Twelve-e': ['ep12', 'East Pacific']}

h_2010 = {'Agatha': ['ep01', 'East Pacific'],
 'Alex': ['al01', 'Atlantic'],
 'Blas': ['ep03', 'East Pacific'],
 'Bonnie': ['al03', 'Atlantic'],
 'Celia': ['ep04', 'East Pacific'],
 'Colin': ['al04', 'Atlantic'],
 'Danielle': ['al06', 'Atlantic'],
 'Darby': ['ep05', 'East Pacific'],
 'Earl': ['al07', 'Atlantic'],
 'Eight-e': ['ep08', 'East Pacific'],
 'Eleven-e': ['ep11', 'East Pacific'],
 'Estelle': ['ep07', 'East Pacific'],
 'Fiona': ['al08', 'Atlantic'],
 'Five': ['al05', 'Atlantic'],
 'Frank': ['ep09', 'East Pacific'],
 'Gaston': ['al09', 'Atlantic'],
 'Georgette': ['ep12', 'East Pacific'],
 'Hermine': ['al10', 'Atlantic'],
 'Igor': ['al11', 'Atlantic'],
 'Julia': ['al12', 'Atlantic'],
 'Karl': ['al13', 'Atlantic'],
 'Lisa': ['al14', 'Atlantic'],
 'Matthew': ['al15', 'Atlantic'],
 'Nicole': ['al16', 'Atlantic'],
 'Otto': ['al17', 'Atlantic'],
 'Paula': ['al18', 'Atlantic'],
 'Richard': ['al19', 'Atlantic'],
 'Shary': ['al20', 'Atlantic'],
 'Six-e': ['ep06', 'East Pacific'],
 'Ten-e': ['ep10', 'East Pacific'],
 'Tomas': ['al21', 'Atlantic'],
 'Two': ['al02', 'Atlantic'],
 'Two-e': ['ep02', 'East Pacific']}

h_2009 = {'Ana': ['al02', 'Atlantic'],
 'Andres': ['ep02', 'East Pacific'],
 'Bill': ['al03', 'Atlantic'],
 'Blanca': ['ep03', 'East Pacific'],
 'Carlos': ['ep04', 'East Pacific'],
 'Claudette': ['al04', 'Atlantic'],
 'Danny': ['al05', 'Atlantic'],
 'Dolores': ['ep05', 'East Pacific'],
 'Eight': ['al08', 'Atlantic'],
 'Enrique': ['ep07', 'East Pacific'],
 'Erika': ['al06', 'Atlantic'],
 'Felicia': ['ep08', 'East Pacific'],
 'Fred': ['al07', 'Atlantic'],
 'Grace': ['al09', 'Atlantic'],
 'Guillermo': ['ep10', 'East Pacific'],
 'Henri': ['al10', 'Atlantic'],
 'Hilda': ['ep11', 'East Pacific'],
 'Ida': ['al11', 'Atlantic'],
 'Ignacio': ['ep12', 'East Pacific'],
 'Jimena': ['ep13', 'East Pacific'],
 'Kevin': ['ep14', 'East Pacific'],
 'Linda': ['ep15', 'East Pacific'],
 'Marty': ['ep16', 'East Pacific'],
 'Nine-e': ['ep09', 'East Pacific'],
 'Nora': ['ep17', 'East Pacific'],
 'Olaf': ['ep18', 'East Pacific'],
 'One': ['al01', 'Atlantic'],
 'One-e': ['ep01', 'East Pacific'],
 'Patricia': ['ep19', 'East Pacific'],
 'Rick': ['ep20', 'East Pacific'],
 'Six-e': ['ep06', 'East Pacific']}

h_2008 = {'Alma': ['ep01', 'East Pacific'],
 'Arthur': ['al01', 'Atlantic'],
 'Bertha': ['al02', 'Atlantic'],
 'Boris': ['ep02', 'East Pacific'],
 'Cristina': ['ep03', 'East Pacific'],
 'Cristobal': ['al03', 'Atlantic'],
 'Dolly': ['al04', 'Atlantic'],
 'Douglas': ['ep04', 'East Pacific'],
 'Edouard': ['al05', 'Atlantic'],
 'Elida': ['ep06', 'East Pacific'],
 'Fausto': ['ep07', 'East Pacific'],
 'Fay': ['al06', 'Atlantic'],
 'Five-e': ['ep05', 'East Pacific'],
 'Genevieve': ['ep08', 'East Pacific'],
 'Gustav': ['al07', 'Atlantic'],
 'Hanna': ['al08', 'Atlantic'],
 'Hernan': ['ep09', 'East Pacific'],
 'Ike': ['al09', 'Atlantic'],
 'Iselle': ['ep10', 'East Pacific'],
 'Josephine': ['al10', 'Atlantic'],
 'Julio': ['ep11', 'East Pacific'],
 'Karina': ['ep12', 'East Pacific'],
 'Kyle': ['al11', 'Atlantic'],
 'Laura': ['al12', 'Atlantic'],
 'Lowell': ['ep13', 'East Pacific'],
 'Marco': ['al13', 'Atlantic'],
 'Marie': ['ep14', 'East Pacific'],
 'Nana': ['al14', 'Atlantic'],
 'Norbert': ['ep15', 'East Pacific'],
 'Odile': ['ep16', 'East Pacific'],
 'Omar': ['al15', 'Atlantic'],
 'Paloma': ['al17', 'Atlantic'],
 'Polo': ['ep18', 'East Pacific'],
 'Seventeen-e': ['ep17', 'East Pacific'],
 'Sixteen': ['al16', 'Atlantic']}