#Dictionaries to store hurricane names

#2019
h_2019 = {  "Andrea" : ["al01", "Atlantic"],
            "Barry" :  ["al02", "Atlantic"],
            "Three" : ["al03", "Atlantic"],
            "Chantal" : ["al04", "Atlantic"],
            "Dorian" : ["al05", "Atlantic"],
            "Erin" : ["al06", "Atlantic"],
            "Fernand" : ["al07", "Atlantic"],
            "Gabrielle" : ["al08", "Atlantic"],
            "Humberto" : ["al09", "Atlantic"],
            "Jerry" : ["al10", "Atlantic"],
            "Imelda" : ["al11", "Atlantic"],
            "Karen" : ["al12", "Atlantic"],
            "Lorenzo" : ["al13", "Atlantic"],
            "Alvin" : ["ep01", "East Pacific"],
            "Barbara" : ["ep02", "East Pacific"],
            "Cosme" : ["ep03", "East Pacific"],
            "Four-e" : ["ep04", "East Pacific"],
            "Dalila" : ["ep05", "East Pacific"],
            "Erick" : ["ep06", "East Pacific"],
            "Flossie" : ["ep07", "East Pacific"],
            "Gil" : ["ep08", "East Pacific"],
            "Henriette" : ["ep09", "East Pacific"],
            "Ivo" : ["ep10", "East Pacific"],
            "Juliette" : ["ep11", "East Pacific"],
            "Akoni" : ["ep12", "East Pacific"],
            "Kiko" : ["ep13", "East Pacific"],
            "Mario" : ["ep14", "East Pacific"],
            "Lorena" : ["ep15", "East Pacific"],
            "Narda" : ["ep16", "East Pacific"]
        }

#Year 2018
h_2018 = {  "Alberto" : ["al01", "Atlantic"],
            "Beryl" :  ["al02", "Atlantic"],
            "Chris" : ["al03", "Atlantic"],
            "Debby" : ["al04", "Atlantic"],
            "Ernesto" : ["al05", "Atlantic"],
            "Florence" : ["al06", "Atlantic"],
            "Gordon" : ["al07", "Atlantic"],
            "Helene" : ["al08", "Atlantic"],
            "Isaac" : ["al09", "Atlantic"],
            "Joyce" : ["al10", "Atlantic"],
            "Eleven" : ["al11", "Atlantic"],
            "Kirk" : ["al12", "Atlantic"],
            "Leslie" : ["al13", "Atlantic"],
            "Michael" : ["al14", "Atlantic"],
            "Nadine" : ["al15", "Atlantic"],
            "Oscar" : ["al16", "Atlantic"],
            "Walaka" : ["ep01", "East Pacific"],
            "Aletta" : ["ep02", "East Pacific"],
            "Bud" : ["ep03", "East Pacific"],
            "Carlotta" : ["ep04", "East Pacific"],
            "Daniel" : ["ep05", "East Pacific"],
            "Emilia" : ["ep06", "East Pacific"],
            "Fabio" : ["ep07", "East Pacific"],
            "Gilma" : ["ep08", "East Pacific"],
            "Nine-e" : ["ep09", "East Pacific"],
            "Hector" : ["ep10", "East Pacific"],
            "Ileana" : ["ep11", "East Pacific"],
            "John" : ["ep12", "East Pacific"],
            "Kristy" : ["ep13", "East Pacific"],
            "Lane" : ["ep14", "East Pacific"],
            "Miriam" : ["ep15", "East Pacific"],
            "Norman" : ["ep16", "East Pacific"],
            "Olivia" : ["ep17", "East Pacific"],
            "Paul" : ["ep18", "East Pacific"],
            "Nineteen-e" : ["ep19", "East Pacific"],
            "Rosa" : ["ep20", "East Pacific"],
            "Sergio" : ["ep21", "East Pacific"],
            "Tara" : ["ep22", "East Pacific"],
            "Vicente" : ["ep23", "East Pacific"],
            "Willa" : ["ep24", "East Pacific"],
            "Xavier" : ["ep25", "East Pacific"]
        }

#Year 2017
h_2017 ={
            "Arlene" : ["al01","Atlantic"],
            "Bret" : ["al02","Atlantic"],
            "Cindy" : ["al03","Atlantic"],
            "Four" : ["al04","Atlantic"],
            "Don" : ["al05","Atlantic"],
            "Emily" : ["al06","Atlantic"],
            "Franklin" : ["al07","Atlantic"],
            "Gert" : ["al08","Atlantic"],
            "Harvey" : ["al09","Atlantic"],
            "Ten" : ["al10","Atlantic"],
            "Irma" : ["al11","Atlantic"],
            "Jose" : ["al12","Atlantic"],
            "Katia" : ["al13","Atlantic"],
            "Lee" : ["al14","Atlantic"],
            "Maria" : ["al15","Atlantic"],
            "Nate" : ["al16","Atlantic"],
            "Ophelia" : ["al17","Atlantic"],
            "Philippe" : ["al18","Atlantic"],
            "Rina" : ["al19","Atlantic"],
            "Adrian" : ["ep01", "East Pacific"],
            "Beatriz" : ["ep02", "East Pacific"],
            "Calvin" : ["ep03", "East Pacific"],
            "Dora" : ["ep04", "East Pacific"],
            "Eugene" : ["ep05", "East Pacific"],
            "Fernanda" : ["ep06", "East Pacific"],
            "Greg" : ["ep07", "East Pacific"],
            "Eight-e" : ["ep08", "East Pacific"],
            "Hilary" : ["ep09", "East Pacific"],
            "Irwin" : ["ep10", "East Pacific"],
            "Eleven-e" : ["ep11", "East Pacific"],
            "Jova" : ["ep12", "East Pacific"],
            "Kenneth" : ["ep13", "East Pacific"],
            "Lidia" : ["ep14", "East Pacific"],
            "Otis" : ["ep15", "East Pacific"],
            "Max" : ["ep16", "East Pacific"],
            "Norma" : ["ep17", "East Pacific"],
            "Pilar" : ["ep18", "East Pacific"],
            "Ramon" : ["ep19", "East Pacific"],
            "Selma" : ["ep20", "East Pacific"]
        }

#Year 2016
h_2016 ={
        "Alex" : ["al01","Atlantic"],
        "Bonnie" : ["al02","Atlantic"],
        "Colin" : ["al03","Atlantic"],
        "Danielle" : ["al04","Atlantic"],
        "Earl" : ["al05","Atlantic"],
        "Fiona" : ["al06","Atlantic"],
        "Gaston" : ["al07","Atlantic"],
        "Eight" : ["al08","Atlantic"],
        "Hermine" : ["al09","Atlantic"],
        "Ian" : ["al10","Atlantic"],
        "Julia" : ["al11","Atlantic"],
        "Karl" : ["al12","Atlantic"],
        "Lisa" : ["al13","Atlantic"],
        "Matthew" : ["al14","Atlantic"],
        "Nicole" : ["al15","Atlantic"],
        "Otto" : ["al16","Atlantic"],
        "One-e" : ["ep01", "East Pacific"],
        "Agatha" : ["ep02", "East Pacific"],
        "Blas" : ["ep03", "East Pacific"],
        "Celia" : ["ep04", "East Pacific"],
        "Darby" : ["ep05", "East Pacific"],
        "Estelle" : ["ep06", "East Pacific"],
        "Frank" : ["ep07", "East Pacific"],
        "Georgette" : ["ep08", "East Pacific"],
        "Howard" : ["ep09", "East Pacific"],
        "Ivette" : ["ep10", "East Pacific"],
        "Javier" : ["ep11", "East Pacific"],
        "Kay" : ["ep12", "East Pacific"],
        "Lester" : ["ep13", "East Pacific"],
        "Madeline" : ["ep14", "East Pacific"],
        "Newton" : ["ep15", "East Pacific"],
        "Orlene" : ["ep16", "East Pacific"],
        "Paine" : ["ep17", "East Pacific"],
        "Roslyn" : ["ep18", "East Pacific"],
        "Ulika" : ["ep19", "East Pacific"],
        "Seymour" : ["ep20", "East Pacific"],
        "Tina" : ["ep21", "East Pacific"],
        "Otto" : ["ep22", "East Pacific"]
	    }

#Year 2015
h_2015 ={
        "Ana" : ["al01","Atlantic"],
        "Bill" : ["al02","Atlantic"],
        "Claudette" : ["al03","Atlantic"],
        "Danny" : ["al04","Atlantic"],
        "Erika" : ["al05","Atlantic"],
        "Fred" : ["al06","Atlantic"],
        "Grace" : ["al07","Atlantic"],
        "Henri" : ["al08","Atlantic"],
        "Nine" : ["al09","Atlantic"],
        "Ida" : ["al10","Atlantic"],
        "Joaquin" : ["al11","Atlantic"],
        "Kate" : ["al12","Atlantic"],
        "Andres" : ["ep01", "East Pacific"],
        "Blanca" : ["ep02", "East Pacific"],
        "Carlos" : ["ep03", "East Pacific"],
        "Four-e" : ["ep04", "East Pacific"],
        "Dolores" : ["ep05", "East Pacific"],
        "Enrique" : ["ep06", "East Pacific"],
        "Felicia" : ["ep07", "East Pacific"],
        "Eight-e" : ["ep08", "East Pacific"],
        "Guillermo" : ["ep09", "East Pacific"],
        "Hilda" : ["ep10", "East Pacific"],
        "Eleven-e" : ["ep11", "East Pacific"],
        "Ignacio" : ["ep12", "East Pacific"],
        "Jimena" : ["ep13", "East Pacific"],
        "Kevin" : ["ep14", "East Pacific"],
        "Linda" : ["ep15", "East Pacific"],
        "Sixteen-e" : ["ep16", "East Pacific"],
        "Marty" : ["ep17", "East Pacific"],
        "Nora" : ["ep18", "East Pacific"],
        "Olaf" : ["ep19", "East Pacific"],
        "Patricia" : ["ep20", "East Pacific"],
        "Rick" : ["ep21", "East Pacific"],
        "Sandra" : ["ep22", "East Pacific"]
	   }

#Year 2014
h_2014 ={
        "Arthur" : ["al01","Atlantic"],
        "Two" : ["al02","Atlantic"],
        "Bertha" : ["al03","Atlantic"],
        "Cristobal" : ["al04","Atlantic"],
        "Dolly" : ["al05","Atlantic"],
        "Edouard" : ["al06","Atlantic"],
        "Fay" : ["al07","Atlantic"],
        "Gonzalo" : ["al08","Atlantic"],
        "Hanna" : ["al09","Atlantic"],
        "Amanda" : ["ep01", "East Pacific"],
        "Boris" : ["ep02", "East Pacific"],
        "Cristina" : ["ep03", "East Pacific"],
        "Douglas" : ["ep04", "East Pacific"],
        "Elida" : ["ep05", "East Pacific"],
        "Fausto" : ["ep06", "East Pacific"],
        "Genevieve" : ["ep07", "East Pacific"],
        "Hernan" : ["ep08", "East Pacific"],
        "Iselle" : ["ep09", "East Pacific"],
        "Julio" : ["ep10", "East Pacific"],
        "Karina" : ["ep11", "East Pacific"],
        "Lowell" : ["ep12", "East Pacific"],
        "Marie" : ["ep13", "East Pacific"],
        "Norbert" : ["ep14", "East Pacific"],
        "Odile" : ["ep15", "East Pacific"],
        "Sixteen-e" : ["ep16", "East Pacific"],
        "Polo" : ["ep17", "East Pacific"],
        "Rachel" : ["ep18", "East Pacific"],
        "Simon" : ["ep19", "East Pacific"],
        "Trudy" : ["ep20", "East Pacific"],
        "Vance" : ["ep21", "East Pacific"]
      }

#Year 2013
h_2013 ={
        "Andrea" : ["al01","Atlantic"],
        "Barry" : ["al02","Atlantic"],
        "Chantal" : ["al03","Atlantic"],
        "Dorian" : ["al04","Atlantic"],
        "Erin" : ["al05","Atlantic"],
        "Fernand" : ["al06","Atlantic"],
        "Gabrielle" : ["al07","Atlantic"],
        "Eight" : ["al08","Atlantic"],
        "Humberto" : ["al09","Atlantic"],
        "Ingrid" : ["al10","Atlantic"],
        "Jerry" : ["al11","Atlantic"],
        "Karen" : ["al12","Atlantic"],
        "Lorenzo" : ["al13","Atlantic"],
        "Melissa" : ["al14","Atlantic"],
        "Alvin" : ["ep01", "East Pacific"],
        "Barbara" : ["ep02", "East Pacific"],
        "Cosme" : ["ep03", "East Pacific"],
        "Dalila" : ["ep04", "East Pacific"],
        "Erick" : ["ep05", "East Pacific"],
        "Flossie" : ["ep06", "East Pacific"],
        "Gil" : ["ep07", "East Pacific"],
        "Henriette" : ["ep08", "East Pacific"],
        "Ivo" : ["ep09", "East Pacific"],
        "Juliette" : ["ep10", "East Pacific"],
        "Kiko" : ["ep11", "East Pacific"],
        "Lorena" : ["ep12", "East Pacific"],
        "Manuel" : ["ep13", "East Pacific"],
        "Narda" : ["ep14", "East Pacific"],
        "Octave" : ["ep15", "East Pacific"],
        "Priscilla" : ["ep16", "East Pacific"],
        "Raymond" : ["ep17", "East Pacific"],
        "Sonia" : ["ep18", "East Pacific"]
	    }

#Year 2012
h_2012 ={
        "Alberto" : ["al01","Atlantic"],
        "Beryl" : ["al02","Atlantic"],
        "Chris" : ["al03","Atlantic"],
        "Debby" : ["al04","Atlantic"],
        "Ernesto" : ["al05","Atlantic"],
        "Florence" : ["al06","Atlantic"],
        "Helene" : ["al07","Atlantic"],
        "Gordon" : ["al08","Atlantic"],
        "Isaac" : ["al09","Atlantic"],
        "Joyce" : ["al10","Atlantic"],
        "Kirk" : ["al11","Atlantic"],
        "Leslie" : ["al12","Atlantic"],
        "Michael" : ["al13","Atlantic"],
        "Nadine" : ["al14","Atlantic"],
        "Oscar" : ["al15","Atlantic"],
        "Patty" : ["al16","Atlantic"],
        "Rafael" : ["al17","Atlantic"],
        "Sandy" : ["al18","Atlantic"],
        "Tony" : ["al19","Atlantic"],
        "Aletta" : ["ep01", "East Pacific"],
        "Bud" : ["ep02", "East Pacific"],
        "Carlotta" : ["ep03", "East Pacific"],
        "Daniel" : ["ep04", "East Pacific"],
        "Emilia" : ["ep05", "East Pacific"],
        "Fabio" : ["ep06", "East Pacific"],
        "Gilma" : ["ep07", "East Pacific"],
        "Hector" : ["ep08", "East Pacific"],
        "Ileana" : ["ep09", "East Pacific"],
        "John" : ["ep10", "East Pacific"],
        "Kristy" : ["ep11", "East Pacific"],
        "Lane" : ["ep12", "East Pacific"],
        "Miriam" : ["ep13", "East Pacific"],
        "Norman" : ["ep14", "East Pacific"],
        "Olivi" : ["ep15", "East Pacific"],
        "Paul" : ["ep16", "East Pacific"],
        "Rosa" : ["ep17", "East Pacific"]
	   }

# 2011
h_2011 ={
        "Arlene" : ["al01","Atlantic"],
        "Bret" : ["al02","Atlantic"],
        "Cindy" : ["al03","Atlantic"],
        "Don" : ["al04","Atlantic"],
        "Emily" : ["al05","Atlantic"],
        "Franklin" : ["al06","Atlantic"],
        "Gert" : ["al07","Atlantic"],
        "Harvey" : ["al08","Atlantic"],
        "Irene" : ["al09","Atlantic"],
        "Ten" : ["al10","Atlantic"],
        "Jose" : ["al11","Atlantic"],
        "Katia" : ["al12","Atlantic"],
        "Lee" : ["al13","Atlantic"],
        "Maria" : ["al14","Atlantic"],
        "Nate" : ["al15","Atlantic"],
        "Ophelia" : ["al16","Atlantic"],
        "Philippe" : ["al17","Atlantic"],
        "Rina" : ["al18","Atlantic"],
        "Sean" : ["al19","Atlantic"],
        "Adrian" : ["ep01", "East Pacific"],
        "Beatriz" : ["ep02", "East Pacific"],
        "Calvin" : ["ep03", "East Pacific"],
        "Dora" : ["ep04", "East Pacific"],
        "Eugene" : ["ep05", "East Pacific"],
        "Frenanda" : ["ep06", "East Pacific"],
        "Greg" : ["ep07", "East Pacific"],
        "Eight-e" : ["ep08", "East Pacific"],
        "Hilary" : ["ep09", "East Pacific"],
        "Jova" : ["ep10", "East Pacific"],
        "Irwin" : ["ep11", "East Pacific"],
        "Twelve-e" : ["ep12", "East Pacific"],
        "Kenneth" : ["ep13", "East Pacific"]
	   }

#Year 2010
h_2010 ={
            "Alex" : ["al01","Atlantic"],
            "Two" : ["al02","Atlantic"],
            "Bonnie" : ["al03","Atlantic"],
            "Colin" : ["al04","Atlantic"],
            "Five" : ["al05","Atlantic"],
            "Danielle" : ["al06","Atlantic"],
            "Earl" : ["al07","Atlantic"],
            "Fiona" : ["al08","Atlantic"],
            "Gaston" : ["al09","Atlantic"],
            "Hermine" : ["al10","Atlantic"],
            "Igor" : ["al11","Atlantic"],
            "Julia" : ["al12","Atlantic"],
            "Karl" : ["al13","Atlantic"],
            "Lisa" : ["al14","Atlantic"],
            "Matthew" : ["al15","Atlantic"],
            "Nicole" : ["al16","Atlantic"],
            "Otto" : ["al17","Atlantic"],
            "Paula" : ["al18","Atlantic"],
            "Richard" : ["al19","Atlantic"],
            "Shary" : ["al20","Atlantic"],
            "Tomas" : ["al21","Atlantic"],
            "Agatha" : ["ep01", "East Pacific"],
            "Two-e" : ["ep02", "East Pacific"],
            "Blas" : ["ep03", "East Pacific"],
            "Celia" : ["ep04", "East Pacific"],
            "Darby" : ["ep05", "East Pacific"],
            "Six-e" : ["ep06", "East Pacific"],
            "Estelle" : ["ep07", "East Pacific"],
            "Eight-e" : ["ep08", "East Pacific"],
            "Frank" : ["ep09", "East Pacific"],
            "Ten-e" : ["ep10", "East Pacific"],
            "Eleven-e" : ["ep11", "East Pacific"],
            "Georgette" : ["ep12", "East Pacific"]
        }


#Year 2009
h_2009 ={
        "One" : ["al01","Atlantic"],
        "Ana" : ["al02","Atlantic"],
        "Bill" : ["al03","Atlantic"],
        "Claudette" : ["al04","Atlantic"],
        "Danny" : ["al05","Atlantic"],
        "Erika" : ["al06","Atlantic"],
        "Fred" : ["al07","Atlantic"],
        "Eight" : ["al08","Atlantic"],
        "Grace" : ["al09","Atlantic"],
        "Henri" : ["al10","Atlantic"],
        "Ida" : ["al11","Atlantic"],
        "One-e" : ["ep01", "East Pacific"],
        "Andres" : ["ep02", "East Pacific"],
        "Blanca" : ["ep03", "East Pacific"],
        "Carlos" : ["ep04", "East Pacific"],
        "Dolores" : ["ep05", "East Pacific"],
        "Six-e" : ["ep06", "East Pacific"],
        "Enrique" : ["ep07", "East Pacific"],
        "Felicia" : ["ep08", "East Pacific"],
        "Nine-e" : ["ep09", "East Pacific"],
        "Guillermo" : ["ep10", "East Pacific"],
        "Hilda" : ["ep11", "East Pacific"],
        "Ignacio" : ["ep12", "East Pacific"],
        "Jimena" : ["ep13", "East Pacific"],
        "Kevin" : ["ep14", "East Pacific"],
        "Linda" : ["ep15", "East Pacific"],
        "Marty" : ["ep16", "East Pacific"],
        "Nora" : ["ep17", "East Pacific"],
        "Olaf" : ["ep18", "East Pacific"],
        "Patricia" : ["ep19", "East Pacific"],
        "Rick" : ["ep20", "East Pacific"]
	    }

#Year 2008
h_2008 ={
        "Arthur" : ["al01","Atlantic"],
        "Bertha" : ["al02","Atlantic"],
        "Cristobal" : ["al03","Atlantic"],
        "Dolly" : ["al04","Atlantic"],
        "Edouard" : ["al05","Atlantic"],
        "Fay" : ["al06","Atlantic"],
        "Gustav" : ["al07","Atlantic"],
        "Hanna" : ["al08","Atlantic"],
        "Ike" : ["al09","Atlantic"],
        "Josephine" : ["al10","Atlantic"],
        "Kyle" : ["al11","Atlantic"],
        "Laura" : ["al12","Atlantic"],
        "Marco" : ["al13","Atlantic"],
        "Nana" : ["al14","Atlantic"],
        "Omar" : ["al15","Atlantic"],
        "Sixteen" : ["al16","Atlantic"],
        "Paloma" : ["al17","Atlantic"],
        "Alma" : ["ep01", "East Pacific"],
        "Boris" : ["ep02", "East Pacific"],
        "Cristina" : ["ep03", "East Pacific"],
        "Douglas" : ["ep04", "East Pacific"],
        "Five-e" : ["ep05", "East Pacific"],
        "Elida" : ["ep06", "East Pacific"],
        "Fausto" : ["ep07", "East Pacific"],
        "Genevieve" : ["ep08", "East Pacific"],
        "Hernan" : ["ep09", "East Pacific"],
        "Iselle" : ["ep10", "East Pacific"],
        "Julio" : ["ep11", "East Pacific"],
        "Karina" : ["ep12", "East Pacific"],
        "Lowell" : ["ep13", "East Pacific"],
        "Marie" : ["ep14", "East Pacific"],
        "Norbert" : ["ep15", "East Pacific"],
        "Odile" : ["ep16", "East Pacific"],
        "Seventeen-e" : ["ep17", "East Pacific"],
        "Polo" : ["ep18", "East Pacific"]
	    }
